on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  backfill:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: bcanseco/github-contribution-graph-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EMAIL: 232410101019@mail.unej.ac.id 
          MAX_DAYS: 365 
          MIN_COMMITS_PER_DAY: 1
          MAX_COMMITS_PER_DAY: 5
          INCLUDE_WEEKENDS: true

  daily_commit:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: bcanseco/github-contribution-graph-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EMAIL: 232410101019@mail.unej.ac.id 
